
import pandas as pd
import numpy as np
import pyodbc
import datetime as dt

pd.set_option("display.max_columns", None) 
pd.set_option("display.max_colwidth", 1000) #huruf dlm column
pd.set_option("display.max_rows", 100)
pd.set_option("display.precision", 2) #2 titik perpuluhan

Test = pd.read_excel(r"C:\\Users\\syahidhalid\\Syahid_PC\\Analytics - FAD\\00. Loan Database\\Data Source\\202504\\Working\\Streamlit_04. Loan Database as at Apr 2025_Final v1.xlsx", sheet_name = "Loan Database", header=1)

#Test.shape

conn = pyodbc.connect(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=10.32.1.51,1455;'
    'DATABASE=mis_db_prod_backup_2024_04_02;'
    'UID=mis_admin;'
    'PWD=Exim1234;'
    'Encrypt=yes;TrustServerCertificate=yes;'
)
#    'SERVER=10.32.1.51,1455;' UAT
#    'DATABASE=mis_db_prod_backup_2024_04_02;'

#    'SERVER=10.20.1.19,1455;' PROD
#    'DATABASE=mis_db_prod;'

cursor = conn.cursor()

Test1 = Test[["cif_number",
"facility_exim_account_num",
"facility_application_sys_code",
"facility_ccris_master_account_num",
"facility_ccris_sub_account_num",
"finance_sap_number",
"cif_company_group",
"cif_name",
"acc_relationship_manager_rm",
"acc_banking_team",
"syndicated_deal",
"acc_nature_acc",
"facility_type_id",
"facility_ccy_id",
"financing_type",
"shariah_concept",
"fund_type",
"incentive",
"program_lending",
"guarantee",
"acc_status",
"ca_post_approval_stage",
"date_ready_utilization",
"acc_disbursement_status",
"facility_amount_approved",
"facility_amount_approved_myr",
"facility_amount_outstanding",
"acc_principal_amount_outstanding",
"acc_contingent_liability_letter_credit_fc",
"acc_contingent_liability_letter_credit_myr",
"acc_contingent_liability_ori",
"acc_contingent_liability_myr",
"acc_receivables_past_due_claim_fc",
"acc_receivable_past_due_claim_myr",
"acc_total_banking_exposure_fc",
"acc_total_banking_exposure_myr",
"acc_accrued_interest_month_fc",
"acc_accrued_interest_month_myr",
"modification_of_loss_fc",
"modification_of_loss_myr",
"acc_accurate_interest",
"acc_accrued_interest_myr",
"acc_penalty",
"acc_penalty_myr",
"acc_penalty_compensation_fc",
"acc_penalty_compensation_myr",
"acc_suspended_interest",
"acc_interest_suspense_myr",
"acc_other_charges",
"acc_other_charges_myr",
"acc_balance_outstanding_audited_fc",
"acc_balance_outstanding_audited_myr",
"acc_credit_loss_laf_ecl",
"acc_credit_loss_laf_ecl_myr",
"acc_credit_loss_cnc_ecl",
"acc_credit_loss_cnc_ecl_myr",
#"not_yet1",
#"not_yet2",
"acc_undrawn_amount_banking_ori",
"acc_undrawn_amount_myr",
"acc_drawdown_fc",
"acc_drawdown_myr",
"acc_cumulative_drawdown",
"acc_cumulative_drawdown_myr",
"acc_repayment_fc",
"acc_repayment_myr",
"acc_cumulative_repayment",
"acc_cumulative_repayment_myr",
"acc_interest_repayment_fc",
"acc_interest_repayment_myr",
'acc_cumulative_interest_repayment_fc',
'acc_cumulative_interest_repayment_myr',
'penalty_repayment',
'penalty_repayment_myr',
'cumulative_penalty',
'cumulative_penalty_myr',
'other_charges_payment',
'other_charges_payment_myr',
'cumulative_other_charges_payment',
'cumulative_other_charges_payment_myr',
# 'ccpt_classification',
# 'acc_rating_origination',
# 'internal_credit_rating',
# 'crms_obligator_risk_rating',
# 'crms_cg_rating',
# 'pd_percent',
# 'lgd_percent',
# 'acc_MFRS9_staging',
# #'bnm_main_sector',
# #'bnm_sub_sector',
# 'oil_and_gas_desc',
# 'oil_and_gas_segmentation',
# #'purpose_financing',
# #'approved_date',
# #'approval_authority',
# #'acc_lo_issuance_date',
# #'acc_date_lo_acceptance',
# #'acc_first_disbursement_date',
# #'acc_first_repayment_date',
# #'acc_availability_period',
# #'acc_facility_agreement_date',
# #'acc_review_date',
# #'acc_watchlist_review_date_approval',
# 'acc_maturity_expired_date',
# 'acc_grace_period',
# 'moratorium_period_month',
# 'moratorium_start_date',
# 'acc_tenure',
# 'acc_payment_frequency_interest',
# 'acc_payment_frequency_principal',
# 'acc_effective_cost_borrowings',
# 'acc_margin',
# 'acc_average_interest_rate',
# 'acc_tadwih_compensation',
# 'cif_operation_country',
# 'facility_country_id',
# 'acc_country_rating',
# 'acc_region',
# 'market_type',
# "classification_cust_type",
# 'cif_cust_type',
# "classification_residency_status",
# "classificationResidencyStatus",
# "cif_residency_status",
# "cif_corporate_type",
# "cif_corporate_status",
# #"justification_corporate_status",
# "dateapp_type",
# #"dateapp_date",
# "dateapp_effectivedate",
# #"dateapp_reason",
# "date_untagged_rr",
# #"justification_untagged",
# "frequency_rr",
# #"acc_date_overdue",
# # "acc_overdue_days",
# # "int_month_in_arrears",
# # "acc_overdue_ori",
# # "acc_overdue_amount_myr",
# #"acc_watchlist_date",
# #"acc_watchlist_reason",
# #"acc_date_delist_watchlist",
# #"acc_date_impaired",
# #"acc_reason_impairment",
# #"acc_partial_writeoff_date",
# #"acc_writeoff_date",
# #"acc_cancel_fulltsettle_date",
# #"position_as_at"
]].fillna(0)



# #checking
# for col in Test1.columns:
#     if np.issubdtype(Test1[col].dtype, np.datetime64):
#         print(f"{col} min: {Test1[col].min()}, max: {Test1[col].max()}")

column_types = []
for col in Test1.columns:
    # You can choose to map column types based on data types in the DataFrame, for example:
    if Test1[col].dtype == 'object':  # String data type
        column_types.append(f"{col} VARCHAR(255)")
    elif Test1[col].dtype == 'int64':  # Integer data type
        column_types.append(f"{col} INT")
    elif Test1[col].dtype == 'float64':  # Float data type
        column_types.append(f"{col} FLOAT")
    else:
        column_types.append(f"{col} VARCHAR(255)")  # Default type for others

# Generate the CREATE TABLE statement
create_table_query = "CREATE TABLE A_MYR (" + ', '.join(column_types) + ")"
# Execute the query
cursor.execute(create_table_query)

for row in Test1.iterrows():
    sql = "INSERT INTO A_MYR({}) VALUES ({})".format(','.join(Test1.columns), ','.join(['?']*len(Test1.columns)))
    cursor.execute(sql, tuple(row[1]))
conn.commit()


cursor.execute("""
MERGE INTO dbase_account_hist AS target
USING A_MYR AS source
ON target.facility_exim_account_num = source.facility_exim_account_num
WHEN MATCHED AND target.position_as_at = '2025-04-30' THEN
    UPDATE SET
        target.cif_number = source.cif_number,
        target.facility_application_sys_code = source.facility_application_sys_code,
        target.facility_ccris_master_account_num = source.facility_ccris_master_account_num,
        target.facility_ccris_sub_account_num = source.facility_ccris_sub_account_num,
        target.finance_sap_number = source.finance_sap_number,
        target.cif_company_group = source.cif_company_group,
        target.cif_name = source.cif_name,
        target.acc_relationship_manager_rm = source.acc_relationship_manager_rm,
        target.acc_banking_team = source.acc_banking_team,
        target.syndicated_deal = source.syndicated_deal,
        target.acc_nature_acc = source.acc_nature_acc,
        target.facility_type_id = source.facility_type_id,
        target.facility_ccy_id = source.facility_ccy_id,
        target.financing_type = source.financing_type,
        target.shariah_concept = source.shariah_concept,
        target.fund_type = source.fund_type,
        target.incentive = source.incentive,
        target.program_lending = source.program_lending,
        target.guarantee = source.guarantee,
        target.acc_status = source.acc_status,
        target.ca_post_approval_stage = source.ca_post_approval_stage,
        target.date_ready_utilization = source.date_ready_utilization,
        target.acc_disbursement_status = source.acc_disbursement_status,
        target.facility_amount_approved = source.facility_amount_approved,
        target.facility_amount_approved_myr = source.facility_amount_approved_myr,
        target.facility_amount_outstanding = source.facility_amount_outstanding,
        target.acc_principal_amount_outstanding = source.acc_principal_amount_outstanding,
        target.acc_contingent_liability_letter_credit_fc = source.acc_contingent_liability_letter_credit_fc,
        target.acc_contingent_liability_letter_credit_myr = source.acc_contingent_liability_letter_credit_myr,
        target.acc_contingent_liability_ori = source.acc_contingent_liability_ori,
        target.acc_contingent_liability_myr = source.acc_contingent_liability_myr,
        target.acc_receivables_past_due_claim_fc = source.acc_receivables_past_due_claim_fc,
        target.acc_receivable_past_due_claim_myr = source.acc_receivable_past_due_claim_myr,
        target.acc_total_banking_exposure_fc = source.acc_total_banking_exposure_fc,
        target.acc_total_banking_exposure_myr = source.acc_total_banking_exposure_myr,
        target.acc_accrued_interest_month_fc = source.acc_accrued_interest_month_fc,
        target.acc_accrued_interest_month_myr = source.acc_accrued_interest_month_myr,
        target.modification_of_loss_fc = source.modification_of_loss_fc,
        target.modification_of_loss_myr = source.modification_of_loss_myr,
        target.acc_accurate_interest = source.acc_accurate_interest,
        target.acc_accrued_interest_myr = source.acc_accrued_interest_myr,
        target.acc_penalty = source.acc_penalty,
        target.acc_penalty_myr = source.acc_penalty_myr,
        target.acc_penalty_compensation_fc = source.acc_penalty_compensation_fc,
        target.acc_penalty_compensation_myr = source.acc_penalty_compensation_myr,
        target.acc_suspended_interest = source.acc_suspended_interest,
        target.acc_interest_suspense_myr = source.acc_interest_suspense_myr,
        target.acc_other_charges = source.acc_other_charges,
        target.acc_other_charges_myr = source.acc_other_charges_myr,
        target.acc_balance_outstanding_audited_fc = source.acc_balance_outstanding_audited_fc,
        target.acc_balance_outstanding_audited_myr = source.acc_balance_outstanding_audited_myr,
        target.acc_credit_loss_laf_ecl = source.acc_credit_loss_laf_ecl,
        target.acc_credit_loss_laf_ecl_myr = source.acc_credit_loss_laf_ecl_myr,
        target.acc_credit_loss_cnc_ecl = source.acc_credit_loss_cnc_ecl,
        target.acc_credit_loss_cnc_ecl_myr = source.acc_credit_loss_cnc_ecl_myr,
        target.acc_undrawn_amount_banking_ori = source.acc_undrawn_amount_banking_ori,
        target.acc_undrawn_amount_myr = source.acc_undrawn_amount_myr,
        target.acc_drawdown_fc = source.acc_drawdown_fc,
        target.acc_drawdown_myr = source.acc_drawdown_myr,
        target.acc_cumulative_drawdown = source.acc_cumulative_drawdown,
        target.acc_cumulative_drawdown_myr = source.acc_cumulative_drawdown_myr,
        target.acc_repayment_fc = source.acc_repayment_fc,
        target.acc_repayment_myr = source.acc_repayment_myr,
        target.acc_cumulative_repayment = source.acc_cumulative_repayment,
        target.acc_cumulative_repayment_myr = source.acc_cumulative_repayment_myr,
        target.acc_interest_repayment_fc = source.acc_interest_repayment_fc,
        target.acc_interest_repayment_myr = source.acc_interest_repayment_myr,
        target.acc_cumulative_interest_repayment_fc = source.acc_cumulative_interest_repayment_fc,
        target.acc_cumulative_interest_repayment_myr = source.acc_cumulative_interest_repayment_myr,
        target.penalty_repayment = source.penalty_repayment,
        target.penalty_repayment_myr = source.penalty_repayment_myr,
        target.cumulative_penalty = source.cumulative_penalty,
        target.cumulative_penalty_myr = source.cumulative_penalty_myr,
        target.other_charges_payment = source.other_charges_payment,
        target.other_charges_payment_myr = source.other_charges_payment_myr,
        target.cumulative_other_charges_payment = source.cumulative_other_charges_payment,
        target.cumulative_other_charges_payment_myr = source.cumulative_other_charges_payment_myr
WHEN NOT MATCHED THEN
    INSERT (
        cif_number,
        facility_exim_account_num,
        facility_application_sys_code,
        facility_ccris_master_account_num,
        facility_ccris_sub_account_num,
        finance_sap_number,
        cif_company_group,
        cif_name,
        acc_relationship_manager_rm,
        acc_banking_team,
        syndicated_deal,
        acc_nature_acc,
        facility_type_id,
        facility_ccy_id,
        financing_type,
        shariah_concept,
        fund_type,
        incentive,
        program_lending,
        guarantee,
        acc_status,
        ca_post_approval_stage,
        date_ready_utilization,
        acc_disbursement_status,
        facility_amount_approved,
        facility_amount_approved_myr,
        facility_amount_outstanding,
        acc_principal_amount_outstanding,
        acc_contingent_liability_letter_credit_fc,
        acc_contingent_liability_letter_credit_myr,
        acc_contingent_liability_ori,
        acc_contingent_liability_myr,
        acc_receivables_past_due_claim_fc,
        acc_receivable_past_due_claim_myr,
        acc_total_banking_exposure_fc,
        acc_total_banking_exposure_myr,
        acc_accrued_interest_month_fc,
        acc_accrued_interest_month_myr,
        modification_of_loss_fc,
        modification_of_loss_myr,
        acc_accurate_interest,
        acc_accrued_interest_myr,
        acc_penalty,
        acc_penalty_myr,
        acc_penalty_compensation_fc,
        acc_penalty_compensation_myr,
        acc_suspended_interest,
        acc_interest_suspense_myr,
        acc_other_charges,
        acc_other_charges_myr,
        acc_balance_outstanding_audited_fc,
        acc_balance_outstanding_audited_myr,
        acc_credit_loss_laf_ecl,
        acc_credit_loss_laf_ecl_myr,
        acc_credit_loss_cnc_ecl,
        acc_credit_loss_cnc_ecl_myr,
        acc_undrawn_amount_banking_ori,
        acc_undrawn_amount_myr,
        acc_drawdown_fc,
        acc_drawdown_myr,
        acc_cumulative_drawdown,
        acc_cumulative_drawdown_myr,
        acc_repayment_fc,
        acc_repayment_myr,
        acc_cumulative_repayment,
        acc_cumulative_repayment_myr,
        acc_interest_repayment_fc,
        acc_interest_repayment_myr,
        acc_cumulative_interest_repayment_fc,
        acc_cumulative_interest_repayment_myr,
        penalty_repayment,
        penalty_repayment_myr,
        cumulative_penalty,
        cumulative_penalty_myr,
        other_charges_payment,
        other_charges_payment_myr,
        cumulative_other_charges_payment,
        cumulative_other_charges_payment_myr,
        position_as_at
    )
    VALUES (
        source.cif_number,
        source.facility_exim_account_num,
        source.facility_application_sys_code,
        source.facility_ccris_master_account_num,
        source.facility_ccris_sub_account_num,
        source.finance_sap_number,
        source.cif_company_group,
        source.cif_name,
        source.acc_relationship_manager_rm,
        source.acc_banking_team,
        source.syndicated_deal,
        source.acc_nature_acc,
        source.facility_type_id,
        source.facility_ccy_id,
        source.financing_type,
        source.shariah_concept,
        source.fund_type,
        source.incentive,
        source.program_lending,
        source.guarantee,
        source.acc_status,
        source.ca_post_approval_stage,
        source.date_ready_utilization,
        source.acc_disbursement_status,
        source.facility_amount_approved,
        source.facility_amount_approved_myr,
        source.facility_amount_outstanding,
        source.acc_principal_amount_outstanding,
        source.acc_contingent_liability_letter_credit_fc,
        source.acc_contingent_liability_letter_credit_myr,
        source.acc_contingent_liability_ori,
        source.acc_contingent_liability_myr,
        source.acc_receivables_past_due_claim_fc,
        source.acc_receivable_past_due_claim_myr,
        source.acc_total_banking_exposure_fc,
        source.acc_total_banking_exposure_myr,
        source.acc_accrued_interest_month_fc,
        source.acc_accrued_interest_month_myr,
        source.modification_of_loss_fc,
        source.modification_of_loss_myr,
        source.acc_accurate_interest,
        source.acc_accrued_interest_myr,
        source.acc_penalty,
        source.acc_penalty_myr,
        source.acc_penalty_compensation_fc,
        source.acc_penalty_compensation_myr,
        source.acc_suspended_interest,
        source.acc_interest_suspense_myr,
        source.acc_other_charges,
        source.acc_other_charges_myr,
        source.acc_balance_outstanding_audited_fc,
        source.acc_balance_outstanding_audited_myr,
        source.acc_credit_loss_laf_ecl,
        source.acc_credit_loss_laf_ecl_myr,
        source.acc_credit_loss_cnc_ecl,
        source.acc_credit_loss_cnc_ecl_myr,
        source.acc_undrawn_amount_banking_ori,
        source.acc_undrawn_amount_myr,
        source.acc_drawdown_fc,
        source.acc_drawdown_myr,
        source.acc_cumulative_drawdown,
        source.acc_cumulative_drawdown_myr,
        source.acc_repayment_fc,
        source.acc_repayment_myr,
        source.acc_cumulative_repayment,
        source.acc_cumulative_repayment_myr,
        source.acc_interest_repayment_fc,
        source.acc_interest_repayment_myr,
        source.acc_cumulative_interest_repayment_fc,
        source.acc_cumulative_interest_repayment_myr,
        source.penalty_repayment,
        source.penalty_repayment_myr,
        source.cumulative_penalty,
        source.cumulative_penalty_myr,
        source.other_charges_payment,
        source.other_charges_payment_myr,
        source.cumulative_other_charges_payment,
        source.cumulative_other_charges_payment_myr,
        '2025-04-30'
    );
""")

conn.commit()

cursor.execute("drop table A_MYR")
conn.commit() 

conn.close()

